# SPDX-License-Identifier: Apache-2.0
"""API key collection and validation for LinkedOut setup.

Handles embedding provider choice (OpenAI vs local nomic), OpenAI API key
validation via a test embedding call, optional Apify key collection, and
secure storage to ``~/linkedout-data/config/secrets.yaml``.

All operations are idempotent:
- Detects existing keys and offers to keep or replace
- Detects existing embedding provider choice and offers to change
"""
from __future__ import annotations

import getpass
import os
import re
import stat
import time
from pathlib import Path

import yaml

from linkedout.setup.logging_integration import get_setup_logger
from shared.utilities.operation_report import OperationCounts, OperationReport

# ── Prompt text (exact wording from setup-flow-ux.md) ────────────────

_PROMPT_EMBEDDING_PROVIDER = """\
Step 5 of 15: API Key Collection

LinkedOut uses vector embeddings for semantic search ("who do I know
in climate tech?"). Choose an embedding provider:

  [1] OpenAI  (recommended)
      Fast. Uses the Batch API with text-embedding-3-small.
      Cost: ~$0.01 for 1,000 profiles. A typical network of 4,000
      connections costs about $0.04 total, one-time.
      Requires an OpenAI API key.

  [2] Local   (free, slower)
      Uses nomic-embed-text-v1.5 running on your CPU.
      Downloads a ~275 MB model on first use.
      Takes ~5-15 minutes for 4,000 profiles on a typical laptop.
      No API key needed.

Choose embedding provider [1/2] (default: 1): """

_PROMPT_OPENAI_KEY = """\
Enter your OpenAI API key.
You can find it at: https://platform.openai.com/api-keys

OpenAI API key: """

_MSG_OPENAI_KEY_VALID = "  \u2713 OpenAI API key validated (test embedding succeeded)"

_MSG_OPENAI_KEY_INVALID = """\
  \u2717 OpenAI API key invalid: {error}

  Check that your key is correct and has not been revoked.
  Get a new key at: https://platform.openai.com/api-keys

  Options:
    [1] Enter a different key
    [2] Switch to local embeddings (free, no key needed)

  Choice [1/2]: """

_PROMPT_APIFY_KEY = """\
Apify API key (optional)

Apify enriches LinkedIn profiles with data beyond what the
Voyager API provides (full work history, education details,
skills). The Chrome extension crawls profiles directly via
LinkedIn's API \u2014 Apify is used only for deeper enrichment.

Cost: ~$4 per 1,000 profiles. Apify gives $5 free credit
per account per month \u2014 enough for ~1,250 profiles.

Skip this if you are not planning to use the Chrome extension.
You can always add this key later in ~/linkedout-data/config/secrets.yaml.

Enter Apify API key (or press Enter to skip): """

_SECRETS_YAML_HEADER = """\
# LinkedOut Secrets \u2014 chmod 600
# Generated by /linkedout-setup on {date}
# These values can also be set as environment variables.
"""


def prompt_embedding_provider() -> str:
    """Prompt the user to choose an embedding provider.

    Returns:
        ``"openai"`` or ``"local"``.
    """
    while True:
        try:
            choice = input(_PROMPT_EMBEDDING_PROVIDER).strip()
        except (EOFError, KeyboardInterrupt):
            choice = ""  # default to openai
        if choice in ('', '1'):
            return 'openai'
        if choice == '2':
            return 'local'
        print("  Please enter 1 or 2.")


def collect_openai_key() -> str | None:
    """Prompt for an OpenAI API key, validate it, and return it.

    On validation failure, offers retry or switch to local. Returns
    ``None`` if the user switches to local embeddings.
    """
    while True:
        try:
            key = getpass.getpass(_PROMPT_OPENAI_KEY)
        except (EOFError, KeyboardInterrupt):
            print("\n  No key entered. Switching to local embeddings.")
            return None
        if not key.strip():
            print("  No key entered. Switching to local embeddings.")
            return None

        key = key.strip()
        if validate_openai_key(key):
            print(_MSG_OPENAI_KEY_VALID)
            return key

        # Validation failed — offer retry or switch
        error_msg = "validation failed"
        try:
            choice = input(_MSG_OPENAI_KEY_INVALID.format(error=error_msg)).strip()
        except (EOFError, KeyboardInterrupt):
            choice = "2"  # default to switching to local
        if choice == '2':
            return None
        # Default to retry (choice '1' or anything else)


def validate_openai_key(key: str) -> bool:
    """Validate an OpenAI API key by making a test embedding call.

    Uses the Phase 5 ``OpenAIEmbeddingProvider`` to make a real API call
    with a short test string. Returns ``True`` if the call succeeds.

    Args:
        key: The OpenAI API key to validate.

    Returns:
        ``True`` if the key produces a valid embedding, ``False`` otherwise.
    """
    log = get_setup_logger('api_keys')
    try:
        # Set key in environment temporarily for the provider to pick up
        original = os.environ.get('OPENAI_API_KEY')
        os.environ['OPENAI_API_KEY'] = key
        try:
            from utilities.llm_manager.openai_embedding_provider import OpenAIEmbeddingProvider
            provider = OpenAIEmbeddingProvider()
            result = provider.embed_single("LinkedOut setup validation test")
            return isinstance(result, list) and len(result) > 0
        finally:
            # Restore original env
            if original is not None:
                os.environ['OPENAI_API_KEY'] = original
            else:
                os.environ.pop('OPENAI_API_KEY', None)
    except Exception as e:
        # Log the error type but never the key itself
        log.debug("OpenAI key validation failed: {}", type(e).__name__)
        return False


def collect_apify_key() -> str | None:
    """Prompt for an optional Apify API key.

    Returns:
        The Apify key string, or ``None`` if the user skips.
    """
    try:
        key = getpass.getpass(_PROMPT_APIFY_KEY)
    except (EOFError, KeyboardInterrupt):
        key = ""  # default to skip
    if not key.strip():
        print("  Skipping Apify key. You can add it later in ~/linkedout-data/config/secrets.yaml.")
        return None
    return key.strip()


def write_secrets_yaml(secrets: dict, data_dir: Path) -> Path:
    """Write secrets to ``secrets.yaml`` with restricted permissions.

    Creates or overwrites ``{data_dir}/config/secrets.yaml``. The file
    is always written with ``chmod 600`` (owner read/write only).

    Args:
        secrets: Dictionary of key-value pairs to write. Keys with
            ``None`` values are written as comments.
        data_dir: Root data directory (e.g., ``~/linkedout-data``).

    Returns:
        Path to the written secrets.yaml file.
    """
    log = get_setup_logger('api_keys')
    config_dir = data_dir / 'config'
    config_dir.mkdir(parents=True, exist_ok=True)

    secrets_path = config_dir / 'secrets.yaml'

    from datetime import datetime, timezone
    date_str = datetime.now(timezone.utc).strftime('%Y-%m-%d')

    lines = [_SECRETS_YAML_HEADER.format(date=date_str)]
    lines.append("# \u2500\u2500 API Keys \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500")

    for key, value in secrets.items():
        if value is not None:
            lines.append(f"{key}: {value}")
        else:
            lines.append(f"# {key}:")

    content = '\n'.join(lines) + '\n'
    secrets_path.write_text(content, encoding='utf-8')

    # Enforce restricted permissions
    secrets_path.chmod(stat.S_IRUSR | stat.S_IWUSR)

    log.info("Wrote secrets.yaml to {}", secrets_path)
    return secrets_path


def update_config_yaml(updates: dict, data_dir: Path) -> Path:
    """Update specific values in config.yaml without overwriting the file.

    Reads the existing config, merges ``updates``, and writes back.
    Creates the file if it doesn't exist.

    Args:
        updates: Key-value pairs to set or update.
        data_dir: Root data directory.

    Returns:
        Path to the updated config.yaml.
    """
    log = get_setup_logger('api_keys')
    config_path = data_dir / 'config' / 'config.yaml'

    existing: dict = {}
    if config_path.exists():
        with open(config_path, encoding='utf-8') as f:
            existing = yaml.safe_load(f) or {}

    existing.update(updates)

    # Preserve the file with comments by doing a targeted replacement
    # if the file exists, otherwise write fresh
    if config_path.exists():
        content = config_path.read_text(encoding='utf-8')
        for key, value in updates.items():
            # Replace existing key line or commented-out key line
            pattern = rf'^[#\s]*{re.escape(key)}:.*$'
            replacement = f'{key}: {value}'
            new_content = re.sub(pattern, replacement, content, count=1, flags=re.MULTILINE)
            if new_content != content:
                content = new_content
            elif f'{key}:' not in content:
                # Key not found at all — append before the first blank section
                content = content.rstrip('\n') + f'\n{key}: {value}\n'
        config_path.write_text(content, encoding='utf-8')
    else:
        config_dir = data_dir / 'config'
        config_dir.mkdir(parents=True, exist_ok=True)
        with open(config_path, 'w', encoding='utf-8') as f:
            yaml.dump(existing, f, default_flow_style=False)

    log.info("Updated config.yaml with keys: {}", list(updates.keys()))
    return config_path


def _check_secrets_permissions(secrets_path: Path) -> None:
    """Warn if secrets.yaml has overly permissive file permissions."""
    if not secrets_path.exists():
        return
    mode = secrets_path.stat().st_mode
    if mode & (stat.S_IRGRP | stat.S_IROTH | stat.S_IWGRP | stat.S_IWOTH):
        print(
            f"  \u26a0 {secrets_path} has open permissions.\n"
            f"    Run: chmod 600 {secrets_path}"
        )


def _read_existing_secrets(data_dir: Path) -> dict:
    """Read existing secrets from secrets.yaml if it exists."""
    secrets_path = data_dir / 'config' / 'secrets.yaml'
    if not secrets_path.exists():
        return {}
    try:
        with open(secrets_path, encoding='utf-8') as f:
            return yaml.safe_load(f) or {}
    except (OSError, yaml.YAMLError):
        return {}


def _read_existing_config(data_dir: Path) -> dict:
    """Read existing config from config.yaml if it exists."""
    config_path = data_dir / 'config' / 'config.yaml'
    if not config_path.exists():
        return {}
    try:
        with open(config_path, encoding='utf-8') as f:
            return yaml.safe_load(f) or {}
    except (OSError, yaml.YAMLError):
        return {}


def collect_api_keys(data_dir: Path) -> OperationReport:
    """Full API key collection orchestration.

    Steps:
    1. Choose embedding provider (detect existing choice)
    2. Collect OpenAI key if openai chosen (detect existing key)
    3. Collect Apify key (optional, detect existing)
    4. Write secrets.yaml and update config.yaml

    Args:
        data_dir: Root data directory (e.g., ``~/linkedout-data``).

    Returns:
        OperationReport summarizing what was collected and written.
    """
    log = get_setup_logger('api_keys')
    start = time.monotonic()
    succeeded = 0
    skipped = 0
    next_steps: list[str] = []

    existing_config = _read_existing_config(data_dir)
    existing_secrets = _read_existing_secrets(data_dir)

    # Step 1: Embedding provider choice
    existing_provider = existing_config.get('embedding_provider')
    if existing_provider:
        try:
            change = input(
                f"  Embedding provider is currently set to '{existing_provider}'.\n"
                f"  Change it? [y/N] "
            ).strip().lower()
        except (EOFError, KeyboardInterrupt):
            change = ""  # default to keep existing
        if change in ('y', 'yes'):
            provider = prompt_embedding_provider()
        else:
            provider = existing_provider
            skipped += 1
    else:
        provider = prompt_embedding_provider()

    update_config_yaml({'embedding_provider': provider}, data_dir)
    succeeded += 1

    # Step 2: OpenAI key (if openai chosen)
    secrets: dict[str, str | None] = {}
    openai_key: str | None = None

    if provider == 'openai':
        existing_openai = existing_secrets.get('openai_api_key')
        if existing_openai:
            try:
                change = input(
                    "  An OpenAI API key is already configured.\n"
                    "  Replace it? [y/N] "
                ).strip().lower()
            except (EOFError, KeyboardInterrupt):
                change = ""  # default to keep existing
            if change in ('y', 'yes'):
                openai_key = collect_openai_key()
            else:
                openai_key = existing_openai
                skipped += 1
        else:
            openai_key = collect_openai_key()

        if openai_key is None:
            # User switched to local
            provider = 'local'
            update_config_yaml({'embedding_provider': 'local'}, data_dir)
            log.info("User switched to local embeddings during key collection")
        else:
            secrets['openai_api_key'] = openai_key
            succeeded += 1
    else:
        # Preserve existing OpenAI key if present even when using local
        if existing_secrets.get('openai_api_key'):
            secrets['openai_api_key'] = existing_secrets['openai_api_key']

    # Step 3: Apify key (optional)
    existing_apify = existing_secrets.get('apify_api_key')
    if existing_apify:
        try:
            change = input(
                "  An Apify API key is already configured.\n"
                "  Replace it? [y/N] "
            ).strip().lower()
        except (EOFError, KeyboardInterrupt):
            change = ""  # default to keep existing
        if change in ('y', 'yes'):
            apify_key = collect_apify_key()
        else:
            apify_key = existing_apify
            skipped += 1
    else:
        apify_key = collect_apify_key()

    if apify_key:
        secrets['apify_api_key'] = apify_key
        succeeded += 1
    else:
        secrets['apify_api_key'] = None  # written as comment
        next_steps.append(
            "Add Apify key later if you want Chrome extension enrichment: "
            "~/linkedout-data/config/secrets.yaml"
        )

    # Step 4: Write secrets.yaml
    secrets_path = write_secrets_yaml(secrets, data_dir)
    _check_secrets_permissions(secrets_path)
    succeeded += 1

    duration_ms = (time.monotonic() - start) * 1000

    if provider == 'local':
        next_steps.append(
            "Local embedding model (~275 MB) will be downloaded on first use"
        )

    return OperationReport(
        operation='api-key-collection',
        duration_ms=duration_ms,
        counts=OperationCounts(
            total=succeeded + skipped,
            succeeded=succeeded,
            skipped=skipped,
        ),
        next_steps=next_steps,
    )
