# SPDX-License-Identifier: Apache-2.0
"""Database configuration and setup — all user-space, no sudo.

Handles password generation, config.yaml writing, Alembic migrations,
schema verification, and agent-context.env generation. Designed to be
called after ``scripts/system-setup.sh`` has created the PostgreSQL
user and database.

All operations are idempotent:
- Skips password generation if config.yaml already has a database_url
- Always runs migrations (catches new migrations after upgrade)
- Always regenerates agent-context.env (ensures consistency)
"""
from __future__ import annotations

import os
import secrets
import stat
import subprocess
import time
from pathlib import Path

import yaml

from linkedout.setup.logging_integration import get_setup_logger
from shared.utilities.operation_report import OperationCounts, OperationReport

# Tables that must exist after a successful migration
_REQUIRED_TABLES = (
    'crawled_profile',
    'company',
    'connection',
    'experience',
    'education',
    'profile_skill',
    'role_alias',
    'company_alias',
    'funding_round',
)

_CONFIG_YAML_TEMPLATE = """\
# LinkedOut Configuration
# Generated by /linkedout-setup on {date}
# Env vars override any value here. See: docs/decision/env-config-design.md

# ── Database ─────────────────────────────────────────────
database_url: {database_url}

# ── Data & Logging ───────────────────────────────────────
data_dir: ~/linkedout-data
log_level: INFO            # DEBUG | INFO | WARNING | ERROR
log_format: human          # human | json

# ── Embeddings ───────────────────────────────────────────
embedding_provider: openai   # openai | local
# embedding_model: text-embedding-3-small   # override if needed

# ── LLM ──────────────────────────────────────────────────
# llm_provider: openai
# llm_model: gpt-5.4-2026-03-05

# ── Server (only needed when Chrome extension is active) ─
backend_port: 8001
# backend_host: localhost

# ── Extension Tuning ─────────────────────────────────────
# rate_limit_hourly: 30
# rate_limit_daily: 150
# staleness_days: 30

# ── Demo ─────────────────────────────────────────────────
# demo_mode: false          # true when using demo database

# ── Observability (off by default) ───────────────────────
# langfuse_enabled: false
"""


def generate_password() -> str:
    """Generate a cryptographically secure random password.

    Returns:
        A URL-safe base64-encoded string of at least 32 characters.
    """
    return secrets.token_urlsafe(24)


def set_db_password(password: str) -> None:
    """Set the PostgreSQL password for the 'linkedout' user.

    Connects via peer authentication (no password needed for ALTER)
    and sets the password for the linkedout role.

    Args:
        password: The password to set.
    """
    log = get_setup_logger('database')
    sql = f"ALTER USER linkedout WITH PASSWORD '{password}';"

    try:
        result = subprocess.run(
            ['psql', '-U', 'linkedout', '-d', 'linkedout', '-c', sql],
            capture_output=True,
            text=True,
            timeout=30,
        )
        if result.returncode != 0:
            # Try via postgres superuser if peer auth for linkedout fails
            result = subprocess.run(
                ['sudo', '-u', 'postgres', 'psql', '-d', 'linkedout', '-c', sql],
                capture_output=True,
                text=True,
                timeout=30,
            )
            if result.returncode != 0:
                raise RuntimeError(
                    f'Failed to set database password: {result.stderr.strip()}'
                )
    except FileNotFoundError:
        raise RuntimeError('psql not found. Is PostgreSQL installed?')
    except subprocess.TimeoutExpired:
        raise RuntimeError('Timed out setting database password.')

    log.info('Database password set for user linkedout')


def write_config_yaml(database_url: str, data_dir: Path) -> Path:
    """Write config.yaml with the database URL and defaults.

    Creates ``{data_dir}/config/config.yaml`` with the generated
    database URL and sensible defaults. Sets file permissions to
    owner-only read/write (0600) since it contains the DB password.

    Args:
        database_url: Full PostgreSQL connection string.
        data_dir: Root data directory (e.g., ``~/linkedout-data``).

    Returns:
        Path to the written config.yaml file.
    """
    log = get_setup_logger('database')
    config_dir = data_dir / 'config'
    config_dir.mkdir(parents=True, exist_ok=True)

    config_path = config_dir / 'config.yaml'
    from datetime import datetime, timezone
    date_str = datetime.now(timezone.utc).strftime('%Y-%m-%d')

    content = _CONFIG_YAML_TEMPLATE.format(
        date=date_str,
        database_url=database_url,
    )
    config_path.write_text(content, encoding='utf-8')

    # Restrict permissions: owner read/write only
    config_path.chmod(stat.S_IRUSR | stat.S_IWUSR)

    log.info('Wrote config.yaml to {}', config_path)
    return config_path


def run_migrations(database_url: str) -> OperationReport:
    """Run Alembic migrations against the database.

    Executes ``alembic upgrade head`` with the given DATABASE_URL.
    The working directory is set to the backend root where alembic.ini lives.

    Args:
        database_url: PostgreSQL connection string.

    Returns:
        OperationReport with migration counts.
    """
    log = get_setup_logger('database')
    start = time.monotonic()

    # Find the backend directory (where alembic.ini lives)
    backend_dir = _find_backend_dir()

    env = os.environ.copy()
    env['DATABASE_URL'] = database_url

    try:
        result = subprocess.run(
            ['alembic', 'upgrade', 'head'],
            capture_output=True,
            text=True,
            timeout=120,
            cwd=str(backend_dir),
            env=env,
        )
    except FileNotFoundError:
        # Try with python -m alembic
        result = subprocess.run(
            ['python3', '-m', 'alembic', 'upgrade', 'head'],
            capture_output=True,
            text=True,
            timeout=120,
            cwd=str(backend_dir),
            env=env,
        )

    duration_ms = (time.monotonic() - start) * 1000

    if result.returncode != 0:
        log.error('Alembic migration failed: {}', result.stderr.strip())
        return OperationReport(
            operation='db-migration',
            duration_ms=duration_ms,
            counts=OperationCounts(total=1, failed=1),
            next_steps=['Check migration errors and re-run /linkedout-setup'],
        )

    # Count applied migrations from output
    applied = result.stdout.count('Running upgrade')
    log.info('Applied {} migrations in {:.1f}s', applied, duration_ms / 1000)

    return OperationReport(
        operation='db-migration',
        duration_ms=duration_ms,
        counts=OperationCounts(total=applied, succeeded=applied),
    )


def verify_schema(database_url: str) -> list[str]:
    """Verify that required tables exist in the database.

    Args:
        database_url: PostgreSQL connection string.

    Returns:
        List of missing table names. Empty list means all tables exist.
    """
    log = get_setup_logger('database')
    missing = []

    for table in _REQUIRED_TABLES:
        sql = (
            "SELECT EXISTS ("
            "SELECT 1 FROM information_schema.tables "
            f"WHERE table_name = '{table}'"
            ");"
        )
        try:
            result = subprocess.run(
                ['psql', database_url, '-t', '-A', '-c', sql],
                capture_output=True,
                text=True,
                timeout=10,
            )
            if result.returncode != 0 or 't' not in result.stdout.lower():
                missing.append(table)
        except (FileNotFoundError, subprocess.TimeoutExpired):
            missing.append(table)

    if missing:
        log.warning('Missing tables: {}', ', '.join(missing))
    else:
        log.info('Schema verified: {} tables confirmed', len(_REQUIRED_TABLES))

    return missing


def bootstrap_system_records(database_url: str) -> OperationReport:
    """Insert system tenant, BU, and app_user records if they don't exist.

    These records are FK targets for connection and enrichment_event rows.
    Must be called after migrations succeed and schema is verified.

    Args:
        database_url: PostgreSQL connection string.

    Returns:
        OperationReport with bootstrap counts.
    """
    from dev_tools.db.fixed_data import SYSTEM_APP_USER, SYSTEM_BU, SYSTEM_TENANT

    log = get_setup_logger('database')
    start = time.monotonic()

    from sqlalchemy import create_engine, text

    engine = create_engine(database_url)

    # FK order: tenant -> bu -> app_user
    stmts = [
        text(
            "INSERT INTO tenant (id, name, created_at, updated_at) "
            "VALUES (:id, :name, NOW(), NOW()) "
            "ON CONFLICT (id) DO NOTHING"
        ).bindparams(id=SYSTEM_TENANT['id'], name=SYSTEM_TENANT['name']),
        text(
            "INSERT INTO bu (id, tenant_id, name, created_at, updated_at) "
            "VALUES (:id, :tenant_id, :name, NOW(), NOW()) "
            "ON CONFLICT (id) DO NOTHING"
        ).bindparams(id=SYSTEM_BU['id'], tenant_id=SYSTEM_BU['tenant_id'], name=SYSTEM_BU['name']),
        text(
            "INSERT INTO app_user (id, email, name, auth_provider_id, created_at, updated_at) "
            "VALUES (:id, :email, :name, :auth_provider_id, NOW(), NOW()) "
            "ON CONFLICT (id) DO NOTHING"
        ).bindparams(
            id=SYSTEM_APP_USER['id'],
            email=SYSTEM_APP_USER['email'],
            name=SYSTEM_APP_USER['name'],
            auth_provider_id=SYSTEM_APP_USER['auth_provider_id'],
        ),
    ]

    inserted = 0
    try:
        with engine.begin() as conn:
            for stmt in stmts:
                result = conn.execute(stmt)
                inserted += result.rowcount
        log.info('Bootstrap: {} system records inserted (0 = already existed)', inserted)
    except Exception as e:
        log.error('Bootstrap failed: {}', e)
        duration_ms = (time.monotonic() - start) * 1000
        return OperationReport(
            operation='bootstrap-system-records',
            duration_ms=duration_ms,
            counts=OperationCounts(total=3, failed=3),
            next_steps=['Check bootstrap errors and re-run /linkedout-setup'],
        )
    finally:
        engine.dispose()

    duration_ms = (time.monotonic() - start) * 1000
    return OperationReport(
        operation='bootstrap-system-records',
        duration_ms=duration_ms,
        counts=OperationCounts(total=3, succeeded=3),
    )


def generate_agent_context_env(database_url: str, data_dir: Path) -> Path:
    """Generate agent-context.env for Claude/AI agent DB access.

    Delegates to the shared config module's agent context generator,
    creating a temporary settings object with the given database_url.

    Args:
        database_url: PostgreSQL connection string.
        data_dir: Root data directory.

    Returns:
        Path to the generated agent-context.env file.
    """
    log = get_setup_logger('database')

    # Use the shared agent context generator
    from shared.config.agent_context import generate_agent_context
    from shared.config.settings import LinkedOutSettings

    # Build a settings object with our database_url
    settings = LinkedOutSettings(
        database_url=database_url,
        data_dir=str(data_dir),
    )
    path = generate_agent_context(settings)

    log.info('Wrote agent-context.env to {}', path)
    return path


def setup_database(data_dir: Path) -> OperationReport:
    """Full database setup orchestration.

    Steps:
    1. Generate password (skip if config.yaml already has database_url)
    2. Set PostgreSQL password
    3. Write config.yaml
    4. Run Alembic migrations
    5. Verify schema
    6. Bootstrap system records (tenant, BU, app_user)
    7. Generate agent-context.env

    Args:
        data_dir: Root data directory (e.g., ``~/linkedout-data``).

    Returns:
        OperationReport with overall setup results.
    """
    log = get_setup_logger('database')
    start = time.monotonic()
    succeeded = 0
    failed = 0
    total_steps = 6
    next_steps: list[str] = []

    # Check if config.yaml already exists with a database_url
    config_path = data_dir / 'config' / 'config.yaml'
    existing_url = _read_existing_database_url(config_path)

    if existing_url:
        log.info('Found existing database_url in config.yaml — skipping password generation')
        database_url = existing_url
        succeeded += 1  # password step skipped successfully
    else:
        # Step 1-2: Generate password and set it
        try:
            password = generate_password()
            set_db_password(password)
            database_url = f'postgresql://linkedout:{password}@localhost:5432/linkedout'
            succeeded += 1
        except Exception as e:
            log.error('Failed to set database password: {}', e)
            failed += 1
            # Fall back to no-password URL for local peer auth
            database_url = 'postgresql://linkedout:linkedout@localhost:5432/linkedout'
            next_steps.append('Set the database password manually if needed')

    # Step 3: Write config.yaml (always, to update if needed)
    try:
        write_config_yaml(database_url, data_dir)
        succeeded += 1
    except Exception as e:
        log.error('Failed to write config.yaml: {}', e)
        failed += 1

    # Step 4: Run migrations
    migration_report = run_migrations(database_url)
    if migration_report.counts.failed > 0:
        failed += 1
        next_steps.extend(migration_report.next_steps)
    else:
        succeeded += 1

    # Step 5: Verify schema
    missing = verify_schema(database_url)
    if missing:
        failed += 1
        next_steps.append(f'Missing tables: {", ".join(missing)}. Check migration output.')
    else:
        succeeded += 1

    # Step 6: Bootstrap system records (only if schema is intact)
    if not missing:
        bootstrap_report = bootstrap_system_records(database_url)
        if bootstrap_report.counts.failed > 0:
            failed += 1
            next_steps.extend(bootstrap_report.next_steps)
        else:
            succeeded += 1
    else:
        log.warning('Skipping bootstrap — schema verification failed')
        failed += 1

    # Step 7: Generate agent-context.env (always)
    try:
        generate_agent_context_env(database_url, data_dir)
        succeeded += 1
    except Exception as e:
        log.error('Failed to generate agent-context.env: {}', e)
        failed += 1
        next_steps.append('Generate agent-context.env manually')

    duration_ms = (time.monotonic() - start) * 1000

    return OperationReport(
        operation='db-setup',
        duration_ms=duration_ms,
        counts=OperationCounts(
            total=total_steps + 1,  # +1 for agent-context.env (Step 7)
            succeeded=succeeded,
            failed=failed,
            skipped=0,
        ),
        next_steps=next_steps,
    )


# ── Internal helpers ──────────────────────────────────────────────


def _read_existing_database_url(config_path: Path) -> str | None:
    """Read database_url from an existing config.yaml, if it exists.

    Returns None if the file doesn't exist, is unreadable, or doesn't
    contain a database_url with a password.
    """
    if not config_path.exists():
        return None
    try:
        with open(config_path, encoding='utf-8') as f:
            config = yaml.safe_load(f) or {}
        url = config.get('database_url', '')
        # Only reuse if it has a non-empty password
        if url and '@' in url:
            # Check the password portion is non-empty
            before_at = url.split('@')[0]
            if ':' in before_at:
                password_part = before_at.rsplit(':', 1)[1]
                if password_part:
                    return url
    except (OSError, yaml.YAMLError):
        pass
    return None


def _find_backend_dir() -> Path:
    """Find the backend directory containing alembic.ini.

    Walks up from the current file's location to find the backend root.
    """
    # Start from this file's directory and walk up
    current = Path(__file__).resolve()
    for parent in current.parents:
        candidate = parent / 'alembic.ini'
        if candidate.exists():
            return parent
        # Also check if we're in src/linkedout/setup — go up to backend/
        if (parent / 'backend' / 'alembic.ini').exists():
            return parent / 'backend'
    # Fallback: assume backend/ is relative to repo root
    repo_root = Path(__file__).resolve().parents[4]  # setup -> linkedout -> src -> backend
    if (repo_root / 'alembic.ini').exists():
        return repo_root
    raise FileNotFoundError(
        'Cannot find alembic.ini. Ensure you are running from the repo root.'
    )
