# SPDX-License-Identifier: Apache-2.0
"""Generate agent-context.env for Claude/AI agent DB access."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from shared.config.settings import LinkedOutSettings

# System-level IDs (matches extension/lib/constants.ts)
SYSTEM_TENANT_ID = 'tenant_sys_001'
SYSTEM_BU_ID = 'bu_sys_001'
SYSTEM_USER_ID = 'usr_sys_001'


def generate_agent_context(settings: LinkedOutSettings) -> Path:
    """Write ``agent-context.env`` under ``{data_dir}/config/``.

    The file is designed to be sourced by CLAUDE.md or skill definitions
    so that AI agents get read/write DB access with proper RLS context.

    Overwrites on every call (idempotent).
    """
    config_dir = Path(settings.data_dir) / 'config'
    config_dir.mkdir(parents=True, exist_ok=True)

    path = config_dir / 'agent-context.env'
    path.write_text(
        '# Auto-generated by LinkedOut setup — do not edit manually\n'
        '# Source this file in CLAUDE.md or skill definitions for DB access\n'
        f'DATABASE_URL={settings.database_url}\n'
        f'LINKEDOUT_TENANT_ID={SYSTEM_TENANT_ID}\n'
        f'LINKEDOUT_BU_ID={SYSTEM_BU_ID}\n'
        f'LINKEDOUT_USER_ID={SYSTEM_USER_ID}\n',
    )
    return path
