# SPDX-License-Identifier: Apache-2.0
"""Integration tests for demo database operations.

These tests require a running PostgreSQL instance with pgvector.
They test the full create/restore/stats/drop cycle using the
synthetic test demo dump fixture.

Run with::

    pytest tests/integration/cli/test_demo_db_integration.py -m integration -v
"""
from __future__ import annotations

import shutil
from pathlib import Path
from unittest.mock import patch

import pytest

from linkedout.demo import DEMO_DB_NAME
from linkedout.demo.db_utils import (
    check_pg_restore,
    create_demo_database,
    drop_demo_database,
    get_demo_stats,
    restore_demo_dump,
)

pytestmark = pytest.mark.integration


@pytest.fixture(autouse=True)
def _require_createdb(integration_db_engine):
    """Skip all tests in this module if the DB user lacks CREATEDB privilege."""
    from sqlalchemy import text
    with integration_db_engine.connect() as conn:
        has_priv = conn.execute(
            text("SELECT rolcreatedb FROM pg_roles WHERE rolname = current_user")
        ).scalar()
    if not has_priv:
        pytest.skip("DB user lacks CREATEDB privilege — cannot test demo DB operations")


# Path to the synthetic test dump (generated by generate_test_demo_dump.py)
FIXTURE_DIR = Path(__file__).parent.parent.parent / "fixtures"
TEST_DUMP = FIXTURE_DIR / "demo-seed-test.dump"


def _get_test_db_url() -> str:
    """Get the test database URL from environment."""
    import os
    url = os.environ.get("DATABASE_URL", "")
    if not url or "postgresql" not in url:
        pytest.skip("DATABASE_URL not set or not PostgreSQL")
    return url


@pytest.fixture(scope="module")
def db_url():
    return _get_test_db_url()


class TestDemoCreateDropCycle:
    """Test create and drop of the demo database."""

    def test_create_demo_database(self, db_url):
        """Creating the demo database should return a valid URL."""
        try:
            demo_url = create_demo_database(db_url)
            assert DEMO_DB_NAME in demo_url
        finally:
            drop_demo_database(db_url)

    def test_drop_demo_database(self, db_url):
        """Dropping the demo database should succeed."""
        create_demo_database(db_url)
        result = drop_demo_database(db_url)
        assert result is True

    def test_drop_nonexistent_is_safe(self, db_url):
        """Dropping a non-existent demo DB should succeed (IF EXISTS)."""
        # Ensure it doesn't exist first
        drop_demo_database(db_url)
        result = drop_demo_database(db_url)
        assert result is True


@pytest.mark.skipif(
    not TEST_DUMP.exists(),
    reason="demo-seed-test.dump not found — run generate_test_demo_dump.py first",
)
class TestDemoRestoreCycle:
    """Test restore from the synthetic demo dump fixture."""

    def test_restore_demo_dump(self, db_url):
        """Restoring the synthetic dump should succeed."""
        try:
            demo_url = create_demo_database(db_url)
            result = restore_demo_dump(demo_url, TEST_DUMP)
            assert result is True
        finally:
            drop_demo_database(db_url)

    def test_get_demo_stats_after_restore(self, db_url):
        """After restore, stats should show non-zero counts."""
        try:
            demo_url = create_demo_database(db_url)
            restore_demo_dump(demo_url, TEST_DUMP)
            stats = get_demo_stats(demo_url)

            assert stats["profiles"] > 0
            assert stats["companies"] > 0
        finally:
            drop_demo_database(db_url)

    def test_reset_restores_to_original_state(self, db_url):
        """Drop + create + restore should give the same stats as first restore."""
        try:
            demo_url = create_demo_database(db_url)
            restore_demo_dump(demo_url, TEST_DUMP)
            stats_before = get_demo_stats(demo_url)

            # "Reset" = drop + create + restore
            demo_url = create_demo_database(db_url)
            restore_demo_dump(demo_url, TEST_DUMP)
            stats_after = get_demo_stats(demo_url)

            assert stats_before["profiles"] == stats_after["profiles"]
            assert stats_before["companies"] == stats_after["companies"]
        finally:
            drop_demo_database(db_url)


class TestPrerequisitesPgRestore:
    """Test pg_restore prerequisite check."""

    def test_check_pg_restore_detects_real_binary(self):
        """On a system with PostgreSQL client tools, pg_restore should be found."""
        if shutil.which("pg_restore") is None:
            pytest.skip("pg_restore not installed")
        assert check_pg_restore() is True

    def test_check_pg_restore_missing(self):
        """When pg_restore is not on PATH, should return False."""
        with patch("linkedout.demo.db_utils.shutil.which", return_value=None):
            assert check_pg_restore() is False
